### ISSUE TITLE
request only for  "Facedraw"..

### ISSUE THREAD

**Issue by projectcad** [MariwanJ/nurbs#2]
Hello Mariwan,
Is it possible to make a request only for the command "FaceDraw"..?
Thanks in advance..

https://youtu.be/bPLX3pwUoss

**Comment by MariwanJ** [comment]
Hello, 
I hope you do fine. 
The problem is he used a special translator for a layout he make for all QT GUI. i.e. the graphical interface. That is why some command are missing. Look at the video, you will see that he use some kind of GUI interface. 
I asked the FreeCAD community for help, rather than helping me they started to accuse me that I don't respect Microelly. 
I was mentioning the difficulties I faced, but they wanted to take my words and changed to something else. Which made me very sad and stopped developing the NURBS.
I asked @luzpaz to help me in translating the Germany text.  .. Look at the forum .. No one answered him either. 
I need to get the comment translated to english so I understand more. 
and the QT GUI problem, needs to be fixed. I do that when I get the translation done. 
I know, I started the project to get that functionality working ..unfortunately, I didn't know the quality of the code. 
Using custom-design things is no good. Specially when one put no comment in the code. 
I hope some one help .. but I will not ask anything more at the freecad forum. I don't like the behavior of some people there. They help nothing but they can come and write unwanted comment against you. 
BR

**Comment by projectcad** [comment]
I see there is a too general problem in this WB..Thanks for your explanation..

**Comment by MarcelP102** [comment]
I think the problem comes due to your bad english, due to miscomunication. I told you few days ago in the forum to Ping me (user meetlat) if you are ready to let me translate the german text. You never did.. If I dont get a ping than I don't know that you are ready for me to jump in and start translating. I don't read each post on the forum every day. Besides that you waited not more than 2 days to dicided that no one want's to help you translate. As you used to changed many files each day I think it's best to give others some time to catch up. That's way I sugested to ping me. So you take a break for a minute and let others help you in the small amount of time they have. 

I will try to start translating this weekend, if my girlfriend let me ;) I hope this gives you some motivation.

**Comment by MariwanJ** [comment]
Bad English?  What do you mean? what do you want from my English? what language I use now to communicate with you?
give me an example that I can't English..
My English is not bad .. don't try to use it to as an accuse

I told you that I can not ping/don't know how to do that (wrote that in the Nurbs thread).. and I lost the thread you told me what you are saying now.  
English is my 4th language .. ok I am not an English man but don't say that. 
If someone wants to understand something, he/she will do, if not , they will try to find some accuse

**Comment by luzpaz** [comment]
it's less insulting to tell someone there is a language barrier than saying they're 'bad' a something so casually. They'll get defensive and the original root problem doesn't get addressed. So this is a request for everyone to take *extra time* to mindfully respond to each other.

**Comment by MariwanJ** [comment]
@MarcelP102
Don't waste your time. I will not take any work from you. A person not respect, is not worth to work with.

**Comment by luzpaz** [comment]
@MariwanJ please reconsider your approach and attitude. If language barrier issues continue to make collaboration difficult by collapsing potential opportunities then I fear you'll be working on your own in the long term.

This is open source and that means working together. That means having 'thick skin'.

**Comment by MariwanJ** [comment]
Luzpaz, what language barrier you talk about and what attitude?.  
They did, not me. 
In a world of multi-langue multi cultures, you need to accept that some cannot talk and present themselves like you, even if they can the language.
